# Generated by Django 5.0.1 on 2024-01-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='fecha_inicio_ucamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
